//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorCO2App_Android {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorCO2App_Android.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bluetooth not enabled | ähnelt.
        /// </summary>
        internal static string BluetoothNotEnabled {
            get {
                return ResourceManager.GetString("BluetoothNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bluetooth permission not granted, press red button above ähnelt.
        /// </summary>
        internal static string BluetoothPermissionMissing {
            get {
                return ResourceManager.GetString("BluetoothPermissionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Recording ähnelt.
        /// </summary>
        internal static string CancelRecordingButton {
            get {
                return ResourceManager.GetString("CancelRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to cancel the recording? ähnelt.
        /// </summary>
        internal static string CancelRecordingConfirmationBody {
            get {
                return ResourceManager.GetString("CancelRecordingConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Recording ähnelt.
        /// </summary>
        internal static string CancelRecordingConfirmationHeadline {
            get {
                return ResourceManager.GetString("CancelRecordingConfirmationHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Crash Log to Clipboard ähnelt.
        /// </summary>
        internal static string CopyCrashLogToClipBoardButton {
            get {
                return ResourceManager.GetString("CopyCrashLogToClipBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Debug Log to Clipboard ähnelt.
        /// </summary>
        internal static string CopyDebugLogToClipBoardButton {
            get {
                return ResourceManager.GetString("CopyDebugLogToClipBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Protection Info and Imprint 🔗 ähnelt.
        /// </summary>
        internal static string DataProtectionAndImprintButton {
            get {
                return ResourceManager.GetString("DataProtectionAndImprintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Previous Submission ähnelt.
        /// </summary>
        internal static string DeletePreviousSubmissionButton {
            get {
                return ResourceManager.GetString("DeletePreviousSubmissionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CO2 Levels: ähnelt.
        /// </summary>
        internal static string DeviceInfoLabel_CO2levels {
            get {
                return ResourceManager.GetString("DeviceInfoLabel_CO2levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update in: ähnelt.
        /// </summary>
        internal static string DeviceInfoLabel_UpdateIn {
            get {
                return ResourceManager.GetString("DeviceInfoLabel_UpdateIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor found, but &apos;Smart Home Integration&apos; is disabled.\r\nEnable it using the offical Aranet app ⓘ ähnelt.
        /// </summary>
        internal static string DisabledSmarthomeIntegration {
            get {
                return ResourceManager.GetString("DisabledSmarthomeIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS enabled &amp; location permissions granted. Getting location info. Might take a minute ähnelt.
        /// </summary>
        internal static string DuringFirstGPSLocationUpdate {
            get {
                return ResourceManager.GetString("DuringFirstGPSLocationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Device by Name: ähnelt.
        /// </summary>
        internal static string FilterDeviceByNameLabel {
            get {
                return ResourceManager.GetString("FilterDeviceByNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die initiating first update in ähnelt.
        /// </summary>
        internal static string FirstUpdate {
            get {
                return ResourceManager.GetString("FirstUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS &amp; Bluetooth permissions and status okay ähnelt.
        /// </summary>
        internal static string GPSAndBTOkay {
            get {
                return ResourceManager.GetString("GPSAndBTOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GPS not enabled | ähnelt.
        /// </summary>
        internal static string GPSNotEnabled {
            get {
                return ResourceManager.GetString("GPSNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Map ▲ ähnelt.
        /// </summary>
        internal static string HideMapLabel {
            get {
                return ResourceManager.GetString("HideMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die include 15m before Recording ähnelt.
        /// </summary>
        internal static string Include15mBeforeRecordingToggle {
            get {
                return ResourceManager.GetString("Include15mBeforeRecordingToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location permission missing | ähnelt.
        /// </summary>
        internal static string LocationPermissionMissing {
            get {
                return ResourceManager.GetString("LocationPermissionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update locations request timed out, try again ähnelt.
        /// </summary>
        internal static string LocationSearchTimeout {
            get {
                return ResourceManager.GetString("LocationSearchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locations Found ähnelt.
        /// </summary>
        internal static string LocationsFoundStatus {
            get {
                return ResourceManager.GetString("LocationsFoundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die | low CO2 Value! Sensor might need recalibration  ähnelt.
        /// </summary>
        internal static string LowCO2Levels {
            get {
                return ResourceManager.GetString("LowCO2Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select your CO2-Monitor ähnelt.
        /// </summary>
        internal static string MonitorSelectionLabel {
            get {
                return ResourceManager.GetString("MonitorSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No locations in range ähnelt.
        /// </summary>
        internal static string NoLocationsInRange {
            get {
                return ResourceManager.GetString("NoLocationsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No location selected ähnelt.
        /// </summary>
        internal static string NoSelectedLocation {
            get {
                return ResourceManager.GetString("NoSelectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes: ähnelt.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No transit origin selected ähnelt.
        /// </summary>
        internal static string NoTransitOriginSelected {
            get {
                return ResourceManager.GetString("NoTransitOriginSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Doors / Windows ähnelt.
        /// </summary>
        internal static string OpenDoorsWindowsCheckbox {
            get {
                return ResourceManager.GetString("OpenDoorsWindowsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Map in Browser 🔗 ähnelt.
        /// </summary>
        internal static string OpenMapInBrowserButton {
            get {
                return ResourceManager.GetString("OpenMapInBrowserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor found, but the firmware is outdated.\r\nUpdate it using the official Aranet app ⓘ ähnelt.
        /// </summary>
        internal static string OutDatedFirmware {
            get {
                return ResourceManager.GetString("OutDatedFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  | previous update failed ähnelt.
        /// </summary>
        internal static string PreviousUpdateFailed {
            get {
                return ResourceManager.GetString("PreviousUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string QuickGuidePopupCloseButton {
            get {
                return ResourceManager.GetString("QuickGuidePopupCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick Guide ähnelt.
        /// </summary>
        internal static string QuickGuidePopupHeadline {
            get {
                return ResourceManager.GetString("QuickGuidePopupHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Manual 🔗 ähnelt.
        /// </summary>
        internal static string QuickGuidePopupLinkManual {
            get {
                return ResourceManager.GetString("QuickGuidePopupLinkManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1) if not all icons on the top are green, follow the guidance texts below them or read the manual linked at the bottom ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart1 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2) Select your Sensor Type ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart2 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3) Press &apos;Update Locations&apos; ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart3 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4) Select the Location you want to measure from the result list ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart4 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5) Press &apos;Start Recording&apos; ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart5 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6) Record for at least 5 Minutes (if your sensor is not set to 1 minute update interval it needs to be longer) ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart6 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7) Press &apos;Submit Data&apos; ähnelt.
        /// </summary>
        internal static string QuickGuidePopupPart7 {
            get {
                return ResourceManager.GetString("QuickGuidePopupPart7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick Guide / User Manual ähnelt.
        /// </summary>
        internal static string QuickGuideUserManualButton {
            get {
                return ResourceManager.GetString("QuickGuideUserManualButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location: ähnelt.
        /// </summary>
        internal static string RecordedDataLabel {
            get {
                return ResourceManager.GetString("RecordedDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search Range ähnelt.
        /// </summary>
        internal static string SearchRangeLabel {
            get {
                return ResourceManager.GetString("SearchRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show on map ▼ ähnelt.
        /// </summary>
        internal static string ShowOnMapFoldOut {
            get {
                return ResourceManager.GetString("ShowOnMapFoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Sliders to trim start &amp; end if required ähnelt.
        /// </summary>
        internal static string SliderInfoLabel {
            get {
                return ResourceManager.GetString("SliderInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Recording ähnelt.
        /// </summary>
        internal static string StartRecordingButton {
            get {
                return ResourceManager.GetString("StartRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Transit Recording ähnelt.
        /// </summary>
        internal static string StartTransitRecordingButton {
            get {
                return ResourceManager.GetString("StartTransitRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit data (needs 5 data points) ähnelt.
        /// </summary>
        internal static string SubmitRecordingButtonNotEnoughData {
            get {
                return ResourceManager.GetString("SubmitRecordingButtonNotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit data ähnelt.
        /// </summary>
        internal static string SubmitRecordingButtonOkay {
            get {
                return ResourceManager.GetString("SubmitRecordingButtonOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transit origin:  ähnelt.
        /// </summary>
        internal static string TransitOrigin {
            get {
                return ResourceManager.GetString("TransitOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        internal static string TypeOfTransitAll {
            get {
                return ResourceManager.GetString("TypeOfTransitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bus ähnelt.
        /// </summary>
        internal static string TypeOfTransitBus {
            get {
                return ResourceManager.GetString("TypeOfTransitBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lightrail ähnelt.
        /// </summary>
        internal static string TypeOfTransitLightrail {
            get {
                return ResourceManager.GetString("TypeOfTransitLightrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subway ähnelt.
        /// </summary>
        internal static string TypeOfTransitSubway {
            get {
                return ResourceManager.GetString("TypeOfTransitSubway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Train ähnelt.
        /// </summary>
        internal static string TypeOfTransitTrain {
            get {
                return ResourceManager.GetString("TypeOfTransitTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tram ähnelt.
        /// </summary>
        internal static string TypeOfTransitTram {
            get {
                return ResourceManager.GetString("TypeOfTransitTram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buildings ähnelt.
        /// </summary>
        internal static string TypeSelectionButton_Buildings {
            get {
                return ResourceManager.GetString("TypeSelectionButton_Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transit ähnelt.
        /// </summary>
        internal static string TypeSelectionButton_Transit {
            get {
                return ResourceManager.GetString("TypeSelectionButton_Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die update failed - next attempt in:  ähnelt.
        /// </summary>
        internal static string UpdateFailedNextIn {
            get {
                return ResourceManager.GetString("UpdateFailedNextIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Locations ähnelt.
        /// </summary>
        internal static string UpdateLocationsButton {
            get {
                return ResourceManager.GetString("UpdateLocationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press &apos;Update Locations&apos; to get nearby locations ähnelt.
        /// </summary>
        internal static string UpdateLocationsButtonDefaultInfoLabel {
            get {
                return ResourceManager.GetString("UpdateLocationsButtonDefaultInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select location: ähnelt.
        /// </summary>
        internal static string UpdateLocationsButtonFoundLocationsLabel {
            get {
                return ResourceManager.GetString("UpdateLocationsButtonFoundLocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die currently retrieving nearby locations ähnelt.
        /// </summary>
        internal static string UpdateLocationsButtonSearchingInfoLabel {
            get {
                return ResourceManager.GetString("UpdateLocationsButtonSearchingInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press &apos;Update Locations&apos; to get nearby locations ähnelt.
        /// </summary>
        internal static string UpdateLocationUsageInfo {
            get {
                return ResourceManager.GetString("UpdateLocationUsageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ventilation System ähnelt.
        /// </summary>
        internal static string VentilationSystemCheckBox {
            get {
                return ResourceManager.GetString("VentilationSystemCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die waiting for first data from sensor ähnelt.
        /// </summary>
        internal static string WaitingForFirstUpdate {
            get {
                return ResourceManager.GetString("WaitingForFirstUpdate", resourceCulture);
            }
        }
    }
}
